export enum ErrorCode {
  invalidPackageJSON,
  emptyDir,
  missingEntryFiles,
  missing,
  genericError,
  errorFetchingPackageJSON,
  errorGettingPackageJSONFile,
  parsingPackageJSON,
  requirePermission,
  noEntryPoints,
  resolveFile,
  fileNotFound,
  fileAccessDenied,
  buildFailed,
}
